micronaut:
  application:
    name: efficientTestStartup

mongodb:
  uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}

repository:
  databaseName: "application"
  articleCollectionName: "articles"
  productCollectionName: "products"
